server {
    listen 80;
    listen [::]:80;
    server_name izhsintez-barcodes.ru www.izhsintez-barcodes.ru;
    root /var/www/;
    index index.php index.html index.htm;
    charset UTF-8;

    # Обработка всех запросов
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Обработка PHP файлов
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_pass izhsintez-barcodes-php:9000;

        # Кеширование и заголовки
        expires -1;
        proxy_hide_header "Access-Control-Allow-Origin";
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        add_header Access-Control-Allow-Origin "*";

        try_files $uri =404;
    }

}
